"""followers

Revision ID: 3561f48bc1ba
Revises: 2f09cdbe308b
Create Date: 2018-04-08 20:37:14.012789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3561f48bc1ba'
down_revision = '2f09cdbe308b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
